-- 코드를 작성해주세요
SELECT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
FROM DEVELOPERS AS d
WHERE (d.SKILL_CODE & (SELECT c.CODE FROM SKILLCODES AS c WHERE c.NAME = 'Python')) > 0
    OR (d.SKILL_CODE & (SELECT c.CODE FROM SKILLCODEs AS c WHERE c.NAME = 'C#')) > 0
ORDER BY d.ID ASC;