-- 코드를 작성해주세요
SELECT y.YEAR, y.MAX_SIZE - e.SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA AS e
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
) AS y
ON YEAR(e.DIFFERENTIATION_DATE) = y.YEAR
ORDER BY y.YEAR ASC, YEAR_DEV ASC
;