-- 코드를 입력하세요
SELECT ice_info.INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS fh
    JOIN ICECREAM_INFO AS ice_info
    ON fh.FLAVOR = ice_info.FLAVOR
GROUP BY ice_info.INGREDIENT_TYPE
;